// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafkaconnector.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import kafkaconnector.impl.ConsumerHandler;
import kafkaconnector.proxies.Consumer;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetConsumers extends CustomJavaAction<java.util.List<IMendixObject>>
{
	public GetConsumers(IContext context)
	{
		super(context);
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> consumerList = new ArrayList<IMendixObject>(); 
		
		for (kafkaconnector.impl.Consumer consumer : ConsumerHandler.getConsumers()) {
			Consumer consumerObject = new Consumer(getContext());
			consumerObject.setNumber(consumer.getConsumerNumber());
			consumerObject.setConsumerGroup(consumer.getGroupId());
			consumerObject.setTopic(consumer.getTopic());
			consumerObject.setMicroflow(consumer.getMicroflowName());
			consumerObject.setRunning(consumer.getRunning());
			consumerList.add(consumerObject.getMendixObject());
	    }
		return consumerList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetConsumers";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
