// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafkaconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import kafkaconnector.impl.ProducerHandler;

public class SendMessage extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String topic;
	private java.lang.String key;
	private java.lang.String message;

	public SendMessage(IContext context, java.lang.String topic, java.lang.String key, java.lang.String message)
	{
		super(context);
		this.topic = topic;
		this.key = key;
		this.message = message;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ProducerHandler.send(topic, key, message);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SendMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
